version: 0.2

phases:
  pre_build:
    commands:
      - echo building started
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build